#!/usr/bin/env python3
"""Synthesize a benchmark track whose truth is known by construction.

    analysis/.venv/bin/python analysis/make_fixture.py

WHY. Every other tier of the corpus can vanish — the render set these tools were
first calibrated on was deleted, and `.als` truth still waits on someone to
export audio. A generated fixture means `make analyzercheck` ALWAYS has at least
one track, so the harness itself stays provably wired end to end.

WHAT IT IS AND IS NOT. Clean synthesized tones on an exact grid: the easiest
possible input. It proves the chain (analyze.py -> eval.py -> truth) is
connected and that a correct answer scores as correct. It says NOTHING about
accuracy on real audio — a near-perfect score here is the floor, not evidence.
Treat a REGRESSION here as a real bug; treat a good score as "not broken".
"""
import json, os

import numpy as np
import soundfile as sf

ROOT = os.path.dirname(os.path.abspath(__file__))
SLUG = "_fixture-amfcg"
BPM = 120.0
BEAT = 60.0 / BPM
BAR = 4 * BEAT
SR = 22050

# i VI III VII in A minor, one bar each, looped — the progression the original
# spike in analysis/README.md used, so results stay comparable to it.
PROG = [("A:min", [57, 60, 64]), ("F", [53, 57, 60]), ("C", [48, 52, 55]), ("G", [55, 59, 62])]
LOOPS = 4


def tone(midi, dur, sr=SR):
    t = np.linspace(0, dur, int(sr * dur), endpoint=False)
    f = 440.0 * 2 ** ((midi - 69) / 12)
    # a few harmonics so chroma has something realistic to bite on; a pure sine
    # is an unrealistically easy target even for a fixture
    y = sum(a * np.sin(2 * np.pi * f * h * t) for h, a in ((1, 1.0), (2, 0.5), (3, 0.25), (4, 0.12)))
    env = np.minimum(1.0, np.linspace(0, 40, len(t))) * np.exp(-1.6 * t)
    return y * env


def main():
    d = os.path.join(ROOT, "bench", "tracks", SLUG)
    os.makedirs(d, exist_ok=True)
    audio = np.zeros(int(SR * BAR * len(PROG) * LOOPS) + SR)
    chords = []
    for loop in range(LOOPS):
        for k, (label, pitches) in enumerate(PROG):
            t0 = (loop * len(PROG) + k) * BAR
            i0 = int(t0 * SR)
            for p in pitches:
                y = tone(p, BAR)
                audio[i0:i0 + len(y)] += y * 0.22
            # a click on every beat so beat tracking has an onset grid
            for b in range(4):
                j = int((t0 + b * BEAT) * SR)
                click = np.exp(-np.linspace(0, 30, int(SR * 0.03))) * np.random.default_rng(0).standard_normal(int(SR * 0.03))
                audio[j:j + len(click)] += click * (0.5 if b == 0 else 0.22)
            chords.append([round(t0, 3), round(t0 + BAR, 3), label])
    audio = audio[: int(SR * BAR * len(PROG) * LOOPS)]
    audio /= np.max(np.abs(audio)) * 1.05
    sf.write(os.path.join(d, "audio.wav"), audio, SR)

    end = len(PROG) * LOOPS * BAR
    truth = {
        "bpm": BPM,
        "meter": "4/4",
        "key": "A minor",
        "provenance": "synthetic",
        "notes": "generated by make_fixture.py — truth is exact BY CONSTRUCTION. "
                 "Clean tones on an exact grid: proves the harness is wired, "
                 "NOT that the analyzer is accurate on real audio.",
        "downbeats": [round(i * BAR, 3) for i in range(len(PROG) * LOOPS)],
        "beats": [round(i * BEAT, 3) for i in range(int(end / BEAT))],
        "chords": chords,
        "sections": [[0.0, round(end / 2, 3), "verse"], [round(end / 2, 3), round(end, 3), "chorus"]],
    }
    json.dump(truth, open(os.path.join(d, "truth.json"), "w"), indent=2)
    print(f"wrote {d}/audio.wav ({end:.1f}s) + truth.json")
    print(f"  {BPM} bpm, A minor, {len(chords)} chord events over {LOOPS} loops of Am F C G")


if __name__ == "__main__":
    main()
